config/routes.rb
Rails.application.routes.draw do
  root 'kifus#index'
  resources :users, except: :index
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :kifus, only: [:index, :new, :create, :show, :destroy] do
    resources :comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :kifu
end

app/models/kifu.rb
class Kifu < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_one_attached :kifu
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"
  validates :follower_id, presence: true
  validates :following_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :kifus
  has_many :comments
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships
  has_one_attached :avatar

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :authenticate_user!

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def user_signed_in?
    !current_user.nil?
  end

  def authenticate_user!
    redirect_to signin_path unless user_signed_in?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  
  def create
    comment = current_user.comments.new(comment_params)
    comment.save!
    redirect_to kifu_path(params[:kifu_id]), notice: 'コメントが投稿されました！'
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy if comment.user_id == current_user.id
    redirect_to kifu_path(params[:kifu_id]), notice: 'コメントが削除されました。'
  end

  private

  def comment_params
    params.require(:comment).permit(:comment, :kifu_id)
  end
end

app/controllers/kifus_controller.rb
class KifusController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :destroy]

  def index
    if user_signed_in?
      @kifus = Kifu.all
    else
      redirect_to login_path
    end
  end

  def new
    @kifu = Kifu.new
  end

  def create
    kifu = current_user.kifus.new(kifu_params)
    kifu.save!
    redirect_to root_path, notice: "棋譜が投稿されました！"
  end

  def show
    @kifu = Kifu.find(params[:id])
    @comments = @kifu.comments.includes(:user)
    @comment = Comment.new
  end

  def destroy
    kifu = Kifu.find(params[:id])
    kifu.kifu.purge
    kifu.destroy
    redirect_to root_path, notice: "棋譜を削除しました。"
  end

  private

  def kifu_params
    params.require(:kifu).permit(:sente, :gote, :place, :date, :description, :kifu)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    @user = User.find(params[:relationship][:following_id])
    current_user.follow!(@user)
    redirect_to @user
  end

  def destroy
    @user = Relationship.find(params[:id]).following
    current_user.unfollow!(@user)
    redirect_to @user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to root_path if user_signed_in?
  end

  def create
    user = User.find_by(email: session_params[:email]) 
    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'ログインしました！'
    elsif user.email == 'sample-user@gmail.com'
      session[:user_id] = user.id
      redirect_to root_path, notice: 'ログインしました！'
    else
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_path, notice: 'ログアウトしました。'
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy]

  def new
    redirect_to root_path if user_signed_in?
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.save!
    session[:user_id] = @user.id
    redirect_to @user, notice: "ユーザー登録が完了しました！"
  end

  def show
    @kifus = current_user.kifus.order(created_at: :desc)
  end

  def edit
    redirect_to @user if current_user != @user
  end

  def update
    @user.update!(user_params)
    redirect_to @user, notice: "プロフィールが更新されました！" 
  end

  def destroy
    @user.destroy
    redirect_to root_path, notice: "ユーザー「#{@user.name}」を削除しました。"
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :description, :avatar)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/kifus_helper.rb
module KifusHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/kifus/index.html.haml
- @kifus.each do |kifu|
  .card.mt-4
    .card-body
      %p.card-text
        先手：
        = kifu.sente
      %p.card-text
        後手：
        = kifu.gote
      = link_to '棋譜を見る', kifu_path(kifu), class: 'btn btn-primary'

app/views/kifus/new.html.haml
%h1 棋譜投稿

= form_with model: @kifu, local: true do |f|
  .form-group
    = f.label :sente, '先手'
    = f.text_field :sente, class: 'form-control'
  .form-group
    = f.label :gote, '後手'
    = f.text_field :gote, class: 'form-control'
  .form-group
    = f.label :place, '対局場所'
    = f.text_field :place, class: 'form-control'
  .form-group
    = f.label :date, '対局日時'
    = f.text_field :date, class: 'form-control'
  .form-group
    = f.label :description, '備考'
    = f.text_area :description, class: 'form-control'
  .form-group
    = f.label :kifu, '棋譜'
    = f.file_field :kifu, class: 'form-control-file'
  = f.submit '投稿する', class: 'btn btn-primary'

app/views/kifus/show.html.haml
#board.mx-auto

- if current_user == @kifu.user
  = link_to '棋譜を削除する', @kifu, method: :delete, data: { confirm: "棋譜を削除します。よろしいですか？" }, class: 'btn btn-danger'

.card.mt-4
  .card-body
    %p.card-text
      先手：
      = @kifu.sente
    %p.card-text
      後手：
      = @kifu.gote
    %p.card-text
      対局場所：
      = @kifu.place
    %p.card-text
      対局日時：
      = @kifu.date
    %p.card-text
      備考：
      = @kifu.description

= form_with model: [@kifu, @comment], class: 'mt-5 mb-4' do |f|
  .form-group
    = f.label :comment, 'コメント'
    = f.text_area :comment, class: 'form-control'
    = f.hidden_field :kifu_id, value: @kifu.id
  = f.submit 'コメントする', class: 'btn btn-sm btn-primary'

.comments
  - @comments.each do |comment|
    .comment.d-flex.mb-4
      %span.user-name.pt-1= link_to "#{comment.user.name}", user_path(comment.user)
      %span.comment-text.pt-1.pl-3= comment.comment
      %span.delete-btn.pl-3
        - if comment.user_id == current_user.id
          = link_to 'コメントを削除する', kifu_comment_path(@kifu.id, comment.id), method: :delete, data: { confirm: "コメントを削除しますか？" }, class: 'btn btn-sm btn-danger'

:javascript
  KifuForJS.load("/app/assets/javascripts/jt201409130101.kif", "board");

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Kifulog
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-expand-lg.navbar-dark.bg-secondary
      = link_to 'kifulog', root_path, class: 'navbar-brand mr-auto'
      %button.navbar-toggler{"aria-controls" => "navbarNavDropdown", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarNavDropdown", "data-toggle" => "collapse", :type => "button"}
        %span.navbar-toggler-icon
      #navbarNavDropdown.collapse.navbar-collapse.justify-content-end
        %ul.navbar-nav
          %li.nav-item.active
            = link_to '棋譜を投稿する', new_kifu_path, class: 'nav-link'
          - if user_signed_in?
            %li.nav-item.active
              = link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link'
          - else
            %li.nav-item.active
              = link_to '新規登録', signup_path, class: 'nav-link'
            %li.nav-item.active
              = link_to 'ログイン', login_path, class: 'nav-link'
          
    .container.pt-4
      - if flash.notice.present?
        .alert.alert-success
          = flash.notice
      = yield

app/views/users/edit.html.haml
%h1 プロフィール編集

= form_with model: @user, local: true do |f|
  .form-group
    = f.label :name, 'ユーザー名'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :email, 'メールアドレス'
    = f.text_field :email, class: 'form-control'
  .form-group
    = f.label :description, '自己紹介'
    = f.text_area :description, class: 'form-control', rows: 3  
  .form-group
    = f.label :avatar, 'アバター画像'
    = f.file_field :avatar, class: 'form-control-file'
  = f.submit '更新する', class: 'btn btn-primary'

app/views/users/new.html.haml
%h1 ユーザー新規登録

.card.mx-auto.my-3.p-4.px-5
  = form_with model: @user, local: true do |f|
    .form-group
      = f.label :name, 'ユーザー名'
      = f.text_field :name, class: 'form-control'
    .form-group
      = f.label :email, 'メールアドレス'
      = f.text_field :email, class: 'form-control' 
    .form-group
      = f.label :password, 'パスワード'
      = f.password_field :password, class: 'form-control'
    .form-group
      = f.label :password_confirmation, 'パスワード（確認）'
      = f.password_field :password_confirmation, class: 'form-control'
    = f.submit '登録する', class: 'btn btn-primary mt-3'

app/views/users/show.html.haml
.name.d-flex.justify-content-around
  - if @user.avatar.attached?
    = image_tag @user.avatar
  %h1.pb-3= @user.name
  - unless current_user == @user
    %span.follow_form.pt-1
      - if current_user.following?(@user)
        = form_for(current_user.following_relationships.find_by(following_id: @user.id), html: { method: :delete }) do |f|
          = f.submit "フォロー解除する", class: "btn btn-large btn-danger follow-btn"
      - else
        = form_for(current_user.following_relationships.build(following_id: @user.id)) do |f|
          = f.hidden_field :following_id
          = f.submit "フォローする", class: "btn btn-large btn-primary follow-btn"
  - else
    %span.edit_btn.pt-1
      = link_to 'プロフィールを編集する', edit_user_path, class: 'btn btn-large btn-primary'


%table.table.table-borderless.table-hover.pb-5
  %tbody
    %tr
      %th メールアドレス
      %td= @user.email
    %tr
      %th 自己紹介
      %td= @user.description
    - if current_user == @user
      %tr
        %th
        %td
          %p= link_to 'アカウントを削除する', @user, method: :delete, data: { confirm: "ユーザー「#{@user.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger'

- @kifus.each do |kifu|
  .card.mt-4
    .card-body
      %p.card-text
        先手：
        = kifu.sente
      %p.card-text
        後手：
        = kifu.gote
      = link_to '棋譜を見る', kifu_path(kifu), class: 'btn btn-primary'